server {
    listen 4111;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Otimização de cache para imagens e o PDF
    location ~* \.(jpg|jpeg|png|gif|ico|webp|pdf)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Tratamento de erro básico
    error_page 404 /index.html;
}
